services:
  config-server:
    environment:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_SERVER_BACKEND: native
      CONFIG_NATIVE_SEARCH_LOCATIONS: file:/app/config-server-repo
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  kafka:
    ports:
      - "9092:9092"
