ARG RUNTIME_BASE_IMAGE=microservice-industry-auth-service:0.1.0
FROM ${RUNTIME_BASE_IMAGE}

ARG MODULE_PATH=api-gateway

WORKDIR /app

COPY backend/${MODULE_PATH}/target/*-SNAPSHOT.jar /app/app.jar
COPY README.md /app/README.md
COPY backend/config-server-repo /app/config-server-repo

ENTRYPOINT ["java", "-jar", "app.jar"]
