[build]
base = "frontend"
command = "npm run build"
publish = "dist"

[build.environment]
VITE_APP_ENV = "prod"
VITE_API_GATEWAY_URL = "http://127.0.0.1:8080"
VITE_FRONTEND_PUBLIC_URL = "https://manishrnl-microservice-template.netlify.app"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
