[build]
base = "frontend"
command = "npm run build"
publish = "dist"

[build.environment]
VITE_APP_ENV = "production"
VITE_API_GATEWAY_URL = "https://microservice-industry-level-boiler-plate.onrender.com"
VITE_FRONTEND_PUBLIC_URL = "https://manishrnl-microservice-template.netlify.app"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
