global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]
  - job_name: ai-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ai-service:8086"]
