apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: microservice-platform

patches:
  - path: config-patch.yaml
  - target:
      kind: Ingress
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.localhost
