server:
  port: ${SERVER_PORT:${PORT:8082}}
spring:
  datasource:
    driver-class-name: ${HIBERNATE_DRIVER_NAME:org.postgresql.Driver}
    url: ${USER_DATABASE_URL}
    username: ${USER_DATABASE_USERNAME}
    password: ${USER_DATABASE_PASSWORD}
auth:
  datasource:
    url: ${AUTH_DATABASE_URL}
    username: ${AUTH_DATABASE_USERNAME}
    password: ${AUTH_DATABASE_PASSWORD}
