server:
  port: 8761
spring:
  application:
    name: discovery-server
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLED:ALWAYS}
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"
      - "optional:file:../../.env[.properties]"
  security:
    user:
      name: ${EUREKA_USER:eureka}
      password: ${EUREKA_PASSWORD:eureka_password}
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: ${EUREKA_REGISTER_SELF:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_PEERS:http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka_password}@localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    level: "%5p traceId=%X{traceId:-} spanId=%X{spanId:-} userId=%X{userId:-}"
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(${logging.pattern.level}) %clr([%15.15t]){faint} %clr(%-38.38logger{37}){cyan} %clr(:){faint} %m%n%wEx"
