apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  BACKEND_PUBLIC_URL: "https://api.your-domain.example"
  FRONTEND_PUBLIC_URL: "https://your-frontend.netlify.app"
  FILE_PUBLIC_BASE_URL: "https://api.your-domain.example"
  FILE_DOWNLOAD_BASE_URL: "https://api.your-domain.example"
  SECURITY_COOKIES_SECURE: "true"
  SECURITY_COOKIES_SAME_SITE: "None"
  MAIL_DEBUG: "false"
