ServerName localhost

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://prometheus:9090/
    ProxyPassReverse / http://prometheus:9090/

    <Location />
        AuthType Basic
        AuthName "Prometheus"
        AuthBasicProvider file
        AuthUserFile "/usr/local/apache2/conf/.htpasswd"
        Require valid-user
    </Location>
</VirtualHost>
