ServerName localhost

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://zipkin:9411/
    ProxyPassReverse / http://zipkin:9411/

    <Location />
        AuthType Basic
        AuthName "Zipkin"
        AuthBasicProvider file
        AuthUserFile "/usr/local/apache2/conf/.htpasswd"
        Require valid-user
    </Location>
</VirtualHost>
