apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "platform_password"
  AUTH_DATABASE_PASSWORD: "platform_password"
  USER_DATABASE_PASSWORD: "platform_password"
  NOTIFICATION_DATABASE_PASSWORD: "platform_password"
  PAYMENT_DATABASE_PASSWORD: "platform_password"
  FILE_DATABASE_PASSWORD: "platform_password"
  AI_DATABASE_PASSWORD: "platform_password"
  AUDIT_DATABASE_PASSWORD: "platform_password"

  REDIS_PASSWORD: "redis_password"
  KAFKA_SSL_KEYSTORE_PASSWORD: ""
  KAFKA_SSL_TRUSTSTORE_PASSWORD: ""

  EUREKA_PASSWORD: "eureka_password"
  EUREKA_URL: "http://eureka:eureka_password@discovery-server:8761/eureka"
  EUREKA_PEERS: "http://eureka:eureka_password@discovery-server:8761/eureka"

  CONFIG_ENCRYPT_KEY: "change-me-config-encrypt-key"
  CONFIG_GIT_TOKEN: ""
  USER_DATA_ENCRYPTION_KEY: "change-me-user-data-encryption-key"

  BOOTSTRAP_SUPER_ADMIN_PASSWORD: "Password@123"

  GOOGLE_OAUTH_CLIENT_SECRET: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
  LINKEDIN_OAUTH_CLIENT_SECRET: ""

  GEMINI_API_KEY: ""
  GROQ_API_KEY: ""

  MINIO_ROOT_USER: "platform"
  MINIO_ROOT_PASSWORD: "platform_password"

  BREVO_API_KEY: ""
  BREVO_FROM_EMAIL: ""
  BREVO_PASSWORD: ""
  BREVO_USERNAME: ""

  STRIPE_API_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  STRIPE_SECRET_KEY: ""
